# Site settings
title: Xpiks
email:

description: > # this means to ignore newlines until "baseurl:"
  Cross-platform image keywording software

url: /xpiks

browsers:
- last 4 versions

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Google Analytics
google_universal_analytics: UA-10412407-9
google_universal_analytics_cookiedomain: auto

# Facebook Page
use_facebook_page: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title
permalink: pretty

paginate: 5
paginate_path: "/blog/page/:num/"

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
  topic:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorials"
  - scope:
      path: ""
      type: "topic"
    values:
      layout: "topic"